// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package openapi

import (
	"time"
)

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	// Data The array of assets
	Data []Asset `json:"data"`

	// Responsetime The timestamp of the response
	Responsetime time.Time `json:"responsetime"`

	// Status The status code (0 indicates success)
	Status int `json:"status"`
}

// Asset defines model for Asset.
type Asset struct {
	// Amount The total amount
	Amount string `json:"amount"`

	// Available The available amount
	Available string `json:"available"`

	// ConversionRate The conversion rate
	ConversionRate string `json:"conversionRate"`

	// Symbol The symbol representing the asset
	Symbol string `json:"symbol"`
}

// GetPrivateV1AccountAssetsParams defines parameters for GetPrivateV1AccountAssets.
type GetPrivateV1AccountAssetsParams struct {
	APIKEY       *string `json:"API-KEY,omitempty"`
	APITIMESTAMP *string `json:"API-TIMESTAMP,omitempty"`
	APISIGN      *string `json:"API-SIGN,omitempty"`
}
